HW3
VictoriaStepanova/VictoriaStepanova pull request #6
Opened 2023-02-13 19:03 UTC by VictoriaStepanova

2023-02-14 11:13 UTC, Willynick requested changes

2023-02-14 11:13 UTC, Willynick commented on by/itacademy_hw3/task1intt.java
> +package by.itacademy_hw3;
Тут тоже проблема с пакетами. Смотри предыдущее ДЗ

2023-02-14 11:13 UTC, Willynick commented on by/itacademy_hw3/task1intt.java
> +public class task1intt {
Тоже самое с названиями классов. Лучше просто Task1, Task2 и с большой буквы

2023-02-14 11:13 UTC, Willynick commented on by/itacademy_hw3/task2number.java
> +        double a = sc.nextInt();
Лучше называть переменные по смыслу, а не просто 'a'

2023-02-14 11:13 UTC, Willynick commented on by/itacademy_hw3/task2number.java
> +            System.out.println(Math.signum(- a) + " " + "Число четное отридцательное: ");
Чуть-чуть логика не правильная
![image](https://user-images.githubusercontent.com/57830441/218719531-aa1cac79-b93a-46c4-994e-21e48986552e.png)

2023-02-14 11:13 UTC, Willynick commented on by/itacademy_hw3/task2number.java
> +            System.out.println();
Если хочешь сделать перенос строки - можно использовать символ \n в предыдущей строке

2023-02-14 11:13 UTC, Willynick commented on by/itacademy_hw3/task3week.java
> +        int b = sc.nextInt();
Называть переменные лучше осмысленно, т.е. в данном случае weekDay - например

2023-02-14 11:13 UTC, Willynick commented on by/itacademy_hw3/task3week.java
> +            case 6,7:
Не уверен, что так можно. Лучше:
case 6:
case 7:

2023-02-14 11:13 UTC, Willynick commented on by/itacademy_hw3/task4abc.java
> +        if (b > c) {
Чуть-чуть что-то см логикой
![image](https://user-images.githubusercontent.com/57830441/218720024-b3748eff-e1fe-40a0-ac2e-a995ab45538e.png)

Также не забывай выводить какой-нибудь поясняющий текст в консоль, чтобы было видно, что мы вводим

2023-02-14 11:13 UTC, Willynick commented on by/itacademy_hw3/task6triangle.java
> +            System.out.println("Треугольник существует!");
Тоже не совсем правильная логика
![image](https://user-images.githubusercontent.com/57830441/218720334-9306ca8a-1237-4582-83e3-3df70dc24eb9.png)

2023-02-14 11:13 UTC, Willynick commented on by/itacademy_hw3/task7twoNumber.java
> +        if (a > 0 && a < 9 && b > 0 && b < 9) {
А почему у нас здесь ограничения от 0 до 9?
В условии задачи такого ведь нет

2023-02-20 14:26 UTC, VictoriaStepanova commented on by/itacademy_hw3/task7twoNumber.java
> +        if (a > 0 && a < 9 && b > 0 && b < 9) {
Пользователь вводит два целых однозначных числа. В условиях задачи написано однозначные числа.

2023-04-17 16:56 UTC, merged